services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: workbazar
      POSTGRES_PASSWORD: workbazar
      POSTGRES_DB: workbazar
    ports:
      - "5432:5432"
    volumes:
      - workbazar_pgdata:/var/lib/postgresql/data

volumes:
  workbazar_pgdata:
